import type { Metadata } from "next";
import { Alike_Angular, Artifika } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const alikeAngular = Alike_Angular({
    variable: "--font-alike-angular",
    subsets: [ "latin", "latin-ext" ],
    weight: "400",
});

const artifika = Artifika({
    variable: "--font-artifika",
    subsets: [ "latin" ],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={ `${ alikeAngular.variable } ${ artifika.variable } antialiased` }
        >
        <div className="container">
            {children}
        </div>
        </body>
        </html>
    );
}
